#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'    
echo -e "\e[0;31m ____  ____  ____   "
echo -e "|  _ \|  _ \|  _ \  "
echo -e "| |_) | |_) | |_) | "
echo -e "|  _ <|  _ <|  _ <  "
echo -e "| |_) | |_) | |_) | "
echo -e "|____/|____/|____/  "
echo -e "NOTE: MAKE SURE U CONFIGURE BBBv2.py\n"
echo -e "Start IP: "
read sip
echo -e "End IP: "
read eip
python BBBv2.py $sip $eip