#!/bin/bash 
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'   
echo -e "\e[0;31m ____             _        "
echo -e "|  _ \           | |       "
echo -e "| |_) |_ __ _   _| |_ ___  "
echo -e "|  _ >| '__| | | | __/ _ \ "
echo -e "| |_) | |  | |_| | ||  __/ "
echo -e "|____/|_|   \__,_|\__\___| "
./update
echo
echo "Maximum Process: "
read process
./update $process
