#!/bin/bash 
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[1;37m'
NC='\e[0m'   
exit_script()
{
  echo "* * *Trap * * *"
  ./menu
}

exit_script1()
{
  exit 1
}

Take_input1()
{
clear
while :
do
    clear
echo -e "${RED} _      _____            ____  "
echo -e "${RED}| |    |  __ \     /\   |  _ \ "
echo -e "${RED}| |    | |__) |   /  \  | |_) |"
echo -e "${RED}| |    |  _  /   / /\ \ |  _ < "
echo -e "${RED}| |____| | \ \  / ____ \| |_) |"
echo -e "${RED}|______|_|  \_\/_/    \_\____/ "
echo -e "${RED}   Modded By ${GREEN}LiGhT ${RED}And ${GREEN}Serlo   "
echo -e "[ 1 ] Portscan"
echo -e "[ 2 ] Bruteforce List Of IPs"
echo -e "[ 3 ] BuSyBoX BaNg BuS v2"
    read yourch
    case $yourch in
      1) ./portscan ;;
      2) ./brute ;;
      3) ./bbb ;;
      *) echo "Invalid Selection, Please make another selection";
         echo "Press Enter. . ." ; read ;;
 esac
done
}
trap exit_script 2

Take_input1




